### ISSUE TITLE
tdengine nodejs客户端连接的时候，参数有配置文件的目录， 我看乱写好像也能连接成功？这个参数有什么实际意义吗？

### ISSUE THREAD

**Issue by wacdev** [taosdata/taos-connector-node#42]
tdengine nodejs客户端连接的时候，参数有配置文件的目录，
我看乱写好像也能连接成功？这个参数有什么实际意义吗？

**Comment by sangshuduo** [comment]
有默认值。能否具体描述一下“乱写”都是怎么写的？

**Comment by wacdev** [comment]
![image](https://user-images.githubusercontent.com/127726508/229346180-96c34b55-4631-4204-b8ea-cbe4afb188aa.png)
看上面截图，我 taos 放在docker启动的，mac上没有配置文件，我就想问下这个参数有什么实际意义吗？

没意义我就不写了。

**Comment by sangshuduo** [comment]
> ![image](https://user-images.githubusercontent.com/127726508/229346180-96c34b55-4631-4204-b8ea-cbe4afb188aa.png) 看上面截图，我 taos 放在docker启动的，mac上没有配置文件，我就想问下这个参数有什么实际意义吗？
> 
> 没意义我就不写了。

cfg 可以传其他 taos client 可以配置的参数，如果不需要确实可以不写
